tess:
  api:
    base: http://localhost:3000
    email: chris.child@gmail.com
    token: rqDfvsMbsGqrM34r1Up3
providers:
  - title: 'European Bioinformatics Institute (EBI)'
    url: http://localhost:8000
    image_url: 'https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.3/images/logos/EMBL-EBI/EMBL_EBI_Logo_black.svg'
    description: 'EMBL-EBI provides freely available data from life science experiments, performs basic research in computational biology and offers an extensive user training programme, supporting researchers in academia and industry.'
    content_provider_type: 'organisation'
    node_name: 'EMBL-EBI'
    keywords: ['HDRUK']
